title: <p align="center"> Ritwik Desai </p>
logo: /assets/img/logo.png
description: |
  <p align="center">
  <a href="https://www.linkedin.com/in/ritwikdesai/">LinkedIn</a> |
  <a href="https://github.com/ritwikdesai">GitHub</a>
  <br>   
  Senior Software Engineer at Walmart Global Tech India
  <br>
  </p>
google_analytics:
theme: jekyll-theme-minimal
